### ISSUE TITLE
(msstyles) LibreOffice Scrollbar Issues

### ISSUE THREAD

**Issue by WildByDesign** [Rectify11/Installer#194]
### Description

I have been trying to diagnose a few different (yet possibly related) issues with scrollbars in LibreOffice.

Initially, I noticed the most obvious visual issue with LibreOffice and the Black Rectify msstyles:

![LibreOffice-Rectify-Black](https://github.com/Rectify11/Installer/assets/26308319/3ff07b2b-6fe1-4659-9610-a7c597f451b4)

While digging into that issue, I noticed that Rectify Dark also has a weird mouse-over visual on the scrollbar:

![LibreOffice-Rectify-Dark](https://github.com/Rectify11/Installer/assets/26308319/d497172e-b494-4b38-8230-17b548ec3060)

I checked the default Aero theme to see if it had the weird mouse-over visual, but it does not:

![LibreOffice-Aero](https://github.com/Rectify11/Installer/assets/26308319/303fb826-2da8-4942-b006-6939f1c8755c)

Before I dig into the worst visual issue on the Rectify Black msstyles theme, I want to figure out why the Rectify Dark has the issue with hovering the mouse over the scrollbar track area. If I can understand why that is happening, it might lead to figuring out the issue with the Rectify Black msstyles.

@WinExperiments Since you are intimately familiar with the msstyles (I greatly respect your msstyles work), I believe that you would likely have the best understanding of what is happening and why. In particular, could you have a look at the animated GIF for the Rectify Dark msstyles. I just can't figure out why the mouse-over brings up that visual but there is no visual reaction with Aero on mouse-over. I appreciate your time and your work on this.

### Steps To Reproduce

Hover mouse over scrollbar area of LibreOffice.

### Rectify11 Version

Latest from Actions

### Windows Version

Windows 11 22H2

### Logs

Screenshots added to Description above.

**EDIT:** I had the animated GIFs in spoilers initially, but Github does not seem to show them while in spoilers. So I had to remove the spoilers unfortunately.

**EDIT2:** Clearly, LibreOffice programmed their scrollbars on Windows in a very unusual way compared to other win32 programs. However, it doesn't explain why the mouse-over with Aero theme doesn't bring up any visual for the scrollbar track area. I just can't figure this out. But if we can figure it out, it might help us solve the issue with the Black theme and LibreOffice scrollbars which is a much more pronounced visual glitch.

**Comment by WinExperiments** [comment]
Hi @WildByDesign. I'll explain why you see these issues.

Windows scrollbars are a part of the common controls set and consist of 5 parts (In the case of a vertical scrollbar, there's the top arrow, the top track, the scroll thumb, the bottom track, and the bottom arrow.)

Windows scrollbar parts have 5 states each. First state is the "normal" one, second is the mouseover one, third is the pressed one, fourth is the disabled one, and the fifth is when you mouseover a different part. This last state was added in Vista.

Here are the parts that make up the scrollbars in Rectify11 Dark msstyles. (Order: arrows, thumbs, tracks)
![IMAGE1058](https://github.com/Rectify11/Installer/assets/91428431/92c7204c-df0c-42e5-a7e1-94336c498569)
![IMAGE1068](https://github.com/Rectify11/Installer/assets/91428431/e31423ce-c3e4-44e2-9439-660eb8888930)
![IMAGE1078](https://github.com/Rectify11/Installer/assets/91428431/15eb4d0c-89f7-4c65-9c9d-d44a0d66c3e4)

As you can see, the mouseover, pressed, and "mouseover detection" states in the msstyles have a lighter background.

Here are the same parts in aero.msstyles.
![IMAGE962](https://github.com/Rectify11/Installer/assets/91428431/681a24ab-1060-4a59-805d-5b681002e8d9)
![IMAGE972](https://github.com/Rectify11/Installer/assets/91428431/201a6caa-8ae1-4cec-a51d-d141d260616c)
![IMAGE964](https://github.com/Rectify11/Installer/assets/91428431/985b1e87-3e65-42a2-b74d-a58109b3ba14)

All states use the same background.

LibreOffice seems to use Qt for theming. Qt seems to not use the 5th state of scrollbars, so the other parts still use the 1st state. (example: your mouse is over the thumb, the thumb goes to the 2nd state with a lighter background, the arrows and tracks are supposed to go to the 5th state and have a lighter background as well, but they keep using the first state as the 5th is not present in Qt.)

Black msstyles were made for use with the transparent materials MicaForEveryone supplies, so their scrollbars are translucent. As Windows does not natively support scrollbar textures with an alpha channel, it'll keep drawing the image continuously. This issue was fixed by removing animations, which does not interfere with the alpha channel. Qt seems to override the default animations of the msstyles and use its own.

I hope this helps you.

**Comment by WildByDesign** [comment]
@WinExperiments  Thank you so much for that. That was by far one of the most detailed and informative answers I've gotten on Github. I appreciate the time that put into that for me.

Your answer gave me a great understanding of what was happening and why it was happening. Also, it's made me realize that there is nothing that I can do to fix this issue and also the fact that this is more of a third-party bug and not a bug specific to Rectify11. So for that reason, I will close this issue now.

By the way, the tremendous amount of work that you have put into these msstyles and also the work of everyone else involved in Rectify11 is fantastic. Smooth. Keep up the great work.

Cheers!

**Comment by WildByDesign** [comment]
I decided to dig into this issue again. It is clearly an issue with LibreOffice, but I wanted to use this issue to collect some details that I've come across recently and potentially use those details to file a bug with LibreOffice so that it can get fixed.

The code responsible for the scrollbars is here:
https://github.com/LibreOffice/core/blob/959b30841ae9c5cc1f43928f5e7780abaab4a087/vcl/win/gdi/salnativewidgets-luna.cxx#L458-L566

Interestingly, that file originally dates back 20 years, which explains that "Luna" reference to Windows XP in the filename:
https://github.com/LibreOffice/core/commits/34cf91de3d0d6455004bacda399351101789d751/vcl/win/source/gdi/salnativewidgets-luna.cxx?browsing_rename_history=true&new_path=vcl%2Fwin%2Fgdi%2Fsalnativewidgets-luna.cxx&original_branch=959b30841ae9c5cc1f43928f5e7780abaab4a087&after=34cf91de3d0d6455004bacda399351101789d751+106

@WinExperiments You were 100% right, it appears to be missing the 5th state. I'm not sure which version of Windows that 5th state was introduced in, but that clearly seems to be the issue. I will likely file a bug report with LibreOffice soon so that we can keep track of the issue.

**Comment by WinExperiments** [comment]
Since you mentioned now that LibreOffice uses 20+ year old code for the scrollbars, it probably doesn't support alpha channel at all. Also, the 5th state of scrollbars was added with Windows Vista.
