### ISSUE TITLE
Some maximized windows have bad position on window controls

### ISSUE THREAD

**Issue by TheKamboy** [Rectify11/Installer#232]
### Description

I'm not good at describing things, so here is two images.

Not Maximized:

![image](https://github.com/Rectify11/Installer/assets/89111294/3edda8df-055f-4c3e-92d4-bd2c7e9cf00a)

Maximized:

![image](https://github.com/Rectify11/Installer/assets/89111294/179b6ca8-b039-403a-9114-98a12575322b)
 

### Steps To Reproduce

1. Using a program like Alacritty, Pulsar Editor, etc.
2. Maximize the window

### Rectify11 Version

Version: 3.0 RC2

### Windows Version

Windows 11 22H2 22621.2134

### Logs

There are no logs available, this is after install.

**Comment by WinExperiments** [comment]
I don't think this is a Rectify11 specific bug. What happens here is that titlebars have a height of 22 pixels by default. Ever since Windows Vista, Microsoft has added 4 pixels of padding to the window frames to make them easier to drag and resize. That also makes the non maximized windows have a height of 26 pixels. Padding is removed when you maximize a window. What I think is happening here is that these programs still think the padding exist so they center the buttons as if the titlebar is 26 pixels in height.

**Comment by TheKamboy** [comment]
I don't think that is the case because it wasn't like that before I installed Rectify11.

**Comment by TheKamboy** [comment]
@WinExperiments Without Rectify it isn't an issue

![image](https://github.com/Rectify11/Installer/assets/89111294/4a05db6f-c6a7-4c4c-9e99-8406b38e6458)

The border and buttons actually shrink.

**Comment by TheKamboy** [comment]
@WinExperiments yeah

**Comment by TheKamboy** [comment]
I can get screenshots in a different app if need be.

**Comment by adityaonx** [comment]
@WinExperiments @TheKamboy  Well, this is not a Reactify issue, It's the default windows way of handling Windows.
