### ISSUE TITLE
Fix left indents in file explorer for List view

### ISSUE THREAD

**Issue by tracktor-git** [Rectify11/Installer#383]
Hi there!

Since the introduction of 22H2, Windows Explorer now has left indents when in list view. Microsoft won't fix it for a long time. Is it possible to fix it with Rectify11?  It would be great.

![Screenshot 2023-11-26 105219](https://github.com/Rectify11/Installer/assets/37699848/43ea1a66-765f-4300-932a-50cb8897bd25)

**Comment by WinExperiments** [comment]
That is a Microsoft design choice. Weirdly enough, they changed the ExplorerFrame.dll code itself rather than the DirectUI markup. If you don't know what that is, it's an XML-based markup language for Windows UI components. They could've added that to it, or even removed the item count and separator lines of group headers using it... It would be much better than doing these changes in the code itself. You can replace %systemroot%\System32\ExplorerFrame.dll with the version from build 22000 but you'll lose the ability to use the Windows 11 tabs.
