### ISSUE TITLE
Not Install

### ISSUE THREAD

**Issue by Zuccah** [Rectify11/Installer#439]
### Description

Rectify 11 fail installation, cause of windows defender. This is the "error" code hacktool:win32/patcher 

### Steps To Reproduce

Try to install rectify

### Rectify11 Version

v3

### Windows Version

Windows 11 build 23615.100 22H2 Insider DEV

### Logs

![Immagine 2024-01-16 191301](https://github.com/Rectify11/Installer/assets/147527440/95cb81ee-d356-4ddd-8bdc-f964e4719db0)

**Comment by Rushaway** [comment]
Same issue.

**Comment by zha-ai** [comment]
Same issue.

**Comment by megalofauna** [comment]
I just ran into this issue as well with the same system specs as @Zuccah.

Until the bug is resolved, here are the steps that allowed me to move past this issue:
1. Uninstall Rectify11
2. Uninstall Mica For Everyone (via Settings/Apps/Installed Apps)
3. Restart Windows
4. Run the most recent Rectify11 installer again, making sure to check "themes" and making sure _not_ to check "skip Mica for Everyone installation"

At least I _believe_ are the settings that helped me past the issue detailed above. 

Good luck.

**Comment by Zuccah** [comment]
Thanks Bro!! 😃😃
