### ISSUE TITLE
175% scaling items look so tiny.

### ISSUE THREAD

**Issue by hector-macias1** [Rectify11/Installer#598]
### Description

I have to use my 1440p laptop screen using fractional scaling at 175%. Some items (especially in legacy apps like gpedit or disk management, to name a few) look so tiny.

### Steps To Reproduce

install rectify11 using fractional scaling

### Rectify11 Version

Version: 3.2

### Windows Version

22631.3880

### Logs

![Screenshot 2024-08-10 230854](https://github.com/user-attachments/assets/500e5cea-fdb1-446b-8e8b-16053525ab6e)

Note how the elements are microscopic.

**Comment by WildByDesign** [comment]
Since MS likely doesn’t update code for legacy apps like mmc.exe, there is no perfect solution. However, at least on the very most recent updates to Windows 11, it seems like the original GDI scaling isn’t as horrendous as it once was a year ago or so.

You can try by removing the `mmc.exe.manifest` file from the System32 folder. Keep it somewhere just in case you prefer it after. After removing the file, close any instances of mmc.exe and try those apps again and it should be using the original GDI scaling. I don’t think you have to reboot for the changes to take affect.

Now you can test and see which method looks best for your scaling situation based on your preferences.

GDI scaling will look a bit bigger like you want, but any text rendered will look a bit less sharp. It’s a trade off one way or another.

**Comment by hector-macias1** [comment]
Indeed, removing mmc.exe.manifest restored the original gdi scaling but made text a bit blurry, but I think I can live with that.
